export const set_orderInfo = 'set_orderInfo'

export const get_requireTaskInfoForOrderInfo_success = 'get_requireTaskInfoForOrderInfo_success'
export const get_requireTaskInfoForOrderInfo_failed = 'get_requireTaskInfoForOrderInfo_failed'
export const get_requireTaskInfoForOrderInfo_waiting = 'get_requireTaskInfoForOrderInfo_waiting'
export const get_requireTaskInfoForOrderInfo_error = 'get_requireTaskInfoForOrderInfo_error'

