export const get_paymentList_success='get_paymentList_success'
export const get_paymentList_failed='get_paymentList_failed'
export const get_paymentList_waiting='get_paymentList_waiting'
export const get_paymentList_error='get_paymentList_error'