export const save_sendAddrForNotPrice_success = 'save_sendAddrForNotPrice_success'
export const save_sendAddrForNotPrice_failed = 'save_sendAddrForNotPrice_failed'
export const save_sendAddrForNotPrice_waiting = 'save_sendAddrForNotPrice_waiting'
export const save_sendAddrForNotPrice_error = 'save_sendAddrForNotPrice_error'