export const get_routeTaskListForOrder_success = 'get_routeTaskListForOrder_success'
export const get_routeTaskListForOrder_failed = 'get_routeTaskListForOrder_failed'
export const get_routeTaskListForOrder_error = 'get_routeTaskListForOrder_error'
export const get_routeTaskListForOrder_waiting = 'get_routeTaskListForOrder_waiting'